### ISSUE TITLE
java.util.ArrayList$Itr 문제

### ISSUE THREAD

**Issue by BaekJiheon** [koalanlp/nodejs-support#16]
### 기초정보
- Node.js 버전은요? (Version of the Node.js)? v13.9.0
- KoalaNLP 버전은요? (Version of KoalaNLP)? v2.1.2 (현재 기준 npm에 업로드 되어있는 가장 최신 버전)
- 문제의 유형은 어떤 것인가요? (Type of this issue)?
  - [x] 버그리포트. Bug report
  - [ ] 개선점제안. Idea/Suggestion for a improvement
  - [ ] 사용법질문. Question about using KoalaNLP
  - [ ] 기타. Other

### 재연을 위한 정보
- 어떤 문장을 시도하셨습니까? (Which sentence/paragraph did you try?)
```text
안녕하세요. 눈이 오는 설날 아침입니다.
```
- KoalaNLP를 사용한 코드 부분을 보여주세요. (Please show your code snippet which uses KoalaNLP.)
> Async/Await형 기본 예제를 그대로 사용하였습니다.
```javascript
const {KMR, KKMA} = require('koalanlp/API');
const {initialize} = require('koalanlp/Util');
const {Tagger, Parser} = require('koalanlp/proc');

async function executor(){
    await initialize({packages: {KMR: '2.0.4', KKMA: '2.0.4'}, verbose: true});

    let tagger = new Tagger(KMR);
    let tagged = await tagger("안녕하세요. 눈이 오는 설날 아침입니다.");
    for(const sent of tagged) {
        console.log(sent.toString());
    }

    let parser = new Parser(KKMA);
    let parsed = await parser("안녕하세요. 눈이 오는 설날 아침입니다.");
    for(const sent of parsed){
        console.log(sent.toString());
        for(const dep of sent.dependencies){
            console.log(dep.toString());
        }
    }
}

executor().then(
    () => console.log('finished!'), 
    (error) => console.error('Error Occurred!', error)
);
```

### 본문
- 아래에 본문을 입력해주세요. (Describe your issue here.)

> `src/jvm.js`의 `JVM.toJsArray`함수에서 나타나는 문제입니다. 

Visual Studio 2019 C++ SDK, Windows 10 64bit, OpenJDK 13.0.1을 기준으로 JNI에서 java.util.ArrayList$Itr의 멤버함수를 호출 할 수 없는 현상이 나타납니다.
```text
Error Occurred! Error: Error running instance method
java.lang.IllegalAccessException: JNI attached native thread (null caller frame) cannot access a member of class java.util.ArrayList$Itr (in module java.base) with modifiers "public"
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:406)
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:349)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:642)
        at java.base/java.lang.reflect.Method.invoke(Method.java:559)

    at Function.toJsArray (...\node_modules\koalanlp\jvm.js:86:15)
```

**Comment by nearbydelta** [comment]
Nodejs-koalanlp 2.1.3에 반영되었습니다. 감사합니다.
