### ISSUE TITLE
java.lang.NullPointerException 에러가 발생합니다

### ISSUE THREAD

**Issue by sistinafibel** [koalanlp/nodejs-support#25]
### 기초정보
- Node.js 버전은요? (Version of the Node.js)? 12.18.1
- KoalaNLP 버전은요? (Version of KoalaNLP)? 2.1.3
- 문제의 유형은 어떤 것인가요? (Type of this issue)?
  - [X] 버그리포트. Bug report
  - [ ] 개선점제안. Idea/Suggestion for a improvement
  - [ ] 사용법질문. Question about using KoalaNLP
  - [ ] 기타. Other

### 재연을 위한 정보
- 어떤 문장을 시도하셨습니까? (Which sentence/paragraph did you try?)
```text
안녕하세요. 눈이 오는 설날 아침입니다.
```
- KoalaNLP를 사용한 코드 부분을 보여주세요. (Please show your code snippet which uses KoalaNLP.)
```javascript
import {KMR, KKMA} from 'koalanlp/API';
import {initialize} from 'koalanlp/Util';
import {Tagger, Parser} from 'koalanlp/proc';

async function executor(){
    await initialize({packages: {KMR: '2.0.4', KKMA: '2.0.4'}, verbose: true});

    let tagger = new Tagger(KMR);
    let tagged = await tagger("안녕하세요. 눈이 오는 설날 아침입니다.");
    for(const sent of tagged) {
        console.log(sent.toString());
    }

    let parser = new Parser(KKMA);
    let parsed = await parser("안녕하세요. 눈이 오는 설날 아침입니다.");
    for(const sent of parsed){
        console.log(sent.toString());
        for(const dep of sent.dependencies){
            console.log(dep.toString());
        }
    }
}

executor().then(
    () => console.log('finished!'), 
    (error) => console.error('Error Occurred!', error)
);
```

### 본문
- 아래에 본문을 입력해주세요. (Describe your issue here.)
```
C:\Users\junne\Documents\scraping_instagram\node_modules\java\lib\nodeJavaBridge.js:240
  var fields = SyncCall(clazz, 'getDeclaredFields')();
                                                   ^
Error: Error running instance method
java.lang.NullPointerException
        at java.base/jdk.internal.reflect.Reflection.verifyMemberAccess(Reflection.java:130)
        at java.base/java.lang.reflect.AccessibleObject.slowVerifyAccess(AccessibleObject.java:673)
        at java.base/java.lang.reflect.AccessibleObject.verifyAccess(AccessibleObject.java:666)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:638)
        at java.base/java.lang.reflect.Method.invoke(Method.java:559)
```
java NullPointerException 오류가 발생하고 있습니다. 사용하는 자바는 OpenJDK 12 버전을 사용중이에요.

**Comment by nearbydelta** [comment]
1. 혹시 6행 initialize의 버전 코드를, 다음과 같은 최신 버전 코드로 바꿔서도 동일한 오류가 발생하나요?

```javascript
await initialize({packages: {KMR: '2.1.4', KKMA: '2.1.4'}, verbose: true});
```

> 참고: 최신 버전은 [여기](https://github.com/koalanlp/nodejs-support#packages)서 확인하실 수 있습니다.

2. 사용하시는 OS는 Windows인 것으로 추정되는데 맞는지요? 상황 재연을 위해서 동일한 환경을 설정해보고자 합니다.

**Comment by sistinafibel** [comment]
안녕하세요. 답변 감사합니다

1. 네 최신 버전 코드로 바꿔도 동일하게 java NullPointerException가 발생하고 있습니다.
2. 사용하는 OS는 Windows10을 사용중이고 windwos 가이드대로 설치하였습니다. 
그 과정에서 openJDK 12.0.0을 설치하는 경우 환경설정이 제대로 안맞는 문제가 있었는데 (폴더명은 12로만 표시되나 환경설정은 12.0.0 폴더를 가르킴) 이 부분은 제가 임의로 환경변수를 다시 맞추었고 이후  node-gyp 오류가 발생하여 node-gyp와 windwos-build-tools 네이티브 묘듈도 추가로 설치했어요. 

혹시 가능하시다면 이 부분 가이드도 업데이트 부탁드립니다!
감사합니다.

**Comment by gurumnyang** [comment]
해결 되었나요? 저도 NullPointerException 오류가 발생하고 있습니다
